### ISSUE TITLE
neizdodas izpildīt `npm run dev/build`

### ISSUE THREAD

**Issue by another-pavels** [another-pavels/GroupB-Recepies#4]
Iespējams kaut ko nepareizi daru outputs sāds:
```
root@ubuntu-laravel-22-04:/var/www/html# npm run dev

> dev
> vite

file:///var/www/html/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
Izmantoju tukšu ubuntu-22.04 ar 
`apt install php-json php-bcmath php-bcmath php-json php-mbstring php-common php-tokenizer php-xml php-curl composer nodejs npm`

**Comment by another-pavels** [comment]
Visdrīzāk pie vainas ir manas primitīvas nezināšāna web freimworku izmantošanā. Bet tāpēc esmu šeit un gribu saprast (vajag kādu komentāru). Tiklīdz mācēšu palaist projektu - tā publicēsim arī kādu publisko lapu.

**Comment by another-pavels** [comment]
Tikko pamanīju  nepieciešams node v14 (ne tas kas iet ubuntu-22.04 pēc noklusējuma v12:
```sh
root@ip-10-0-0-82:/var/www/html# npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@vitejs/plugin-vue@4.2.3',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'laravel-vite-plugin@0.7.8',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
```
Ok uzliku versiju 14. Bet tāpat atdurās pret citām atkarībām. 
```sh
root@ip-10-0-0-82:~# node -v
v14.21.3
root@ip-10-0-0-82:/var/www/html# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> esbuild@0.17.19 postinstall /var/www/html/node_modules/esbuild
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm64@0.17.19 (node_modules/@esbuild/android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm64@0.17.19: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/darwin-arm64@0.17.19 (node_modules/@esbuild/darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/darwin-arm64@0.17.19: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/darwin-x64@0.17.19 (node_modules/@esbuild/darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/darwin-x64@0.17.19: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/freebsd-arm64@0.17.19 (node_modules/@esbuild/freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/freebsd-arm64@0.17.19: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/freebsd-x64@0.17.19 (node_modules/@esbuild/freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/freebsd-x64@0.17.19: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-arm@0.17.19 (node_modules/@esbuild/linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-arm@0.17.19: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-arm64@0.17.19 (node_modules/@esbuild/linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-arm64@0.17.19: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-ia32@0.17.19 (node_modules/@esbuild/linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-ia32@0.17.19: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.17.19 (node_modules/@esbuild/linux-loong64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-loong64@0.17.19: wanted {"os":"linux","arch":"loong64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-mips64el@0.17.19 (node_modules/@esbuild/linux-mips64el):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-mips64el@0.17.19: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-ppc64@0.17.19 (node_modules/@esbuild/linux-ppc64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-ppc64@0.17.19: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-riscv64@0.17.19 (node_modules/@esbuild/linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-riscv64@0.17.19: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-s390x@0.17.19 (node_modules/@esbuild/linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-s390x@0.17.19: wanted {"os":"linux","arch":"s390x"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/netbsd-x64@0.17.19 (node_modules/@esbuild/netbsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/netbsd-x64@0.17.19: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/openbsd-x64@0.17.19 (node_modules/@esbuild/openbsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/openbsd-x64@0.17.19: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/sunos-x64@0.17.19 (node_modules/@esbuild/sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/sunos-x64@0.17.19: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/win32-arm64@0.17.19 (node_modules/@esbuild/win32-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/win32-arm64@0.17.19: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/win32-ia32@0.17.19 (node_modules/@esbuild/win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/win32-ia32@0.17.19: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/win32-x64@0.17.19 (node_modules/@esbuild/win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/win32-x64@0.17.19: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-x64@0.17.19 (node_modules/@esbuild/android-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-x64@0.17.19: wanted {"os":"android","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm@0.17.19 (node_modules/@esbuild/android-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm@0.17.19: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 81 packages from 112 contributors and audited 104 packages in 10.035s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```sh
root@ip-10-0-0-82:/var/www/html# npm run build

> @ build /var/www/html
> vite build

vite v4.3.9 building for production...
✓ 39 modules transformed.
✓ built in 1.67s
[vite:css] Failed to load PostCSS config (searchPath: /var/www/html): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /var/www/html/postcss.config.js

(@/var/www/html/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /var/www/html/postcss.config.js

(@/var/www/html/postcss.config.js)
    at load (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36333:11)
    at file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36358:16
    at Array.map (<anonymous>)
    at plugins (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36357:8)
    at processResult (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36427:14)
    at file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36551:14
file: /var/www/html/resources/js/Pages/Recipes/Show.vue?vue&type=style&index=0&lang.css
error during build:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-08T17_01_19_737Z-debug.log
```

**Comment by aigarspl** [comment]
Iespējams, ir nepieciešams uzlikt jaunāko NodeJS LTS versiju (šobrīd v18), cik zinu, ne vienmēr ir pieejama jaunākā versija no Ubuntu repozitorija. Šeit būs saite uz dokumentāciju, kur var dabūt jaunāku versiju: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

**Comment by another-pavels** [comment]
Ar nodejs sanāca aiziet tālāk bet tagad esmu šeit. @edmundss  varbūt kaut kas vēl pietrūkst?:
```sh 
ubuntu@ip-10-0-0-225:/var/www/html$ npm run build

> build
> vite build

\vite v4.3.9 building for production...
✓ 39 modules transformed.
✓ built in 2.79s
[vite:load-fallback] Could not load /resources/js/Components/SecondaryButton.vue (imported by resources/js/Pages/Profile/Partials/DeleteUserForm.vue): ENOENT: no such file or directory, open '/resources/js/Components/SecondaryButton.vue'
error during build:
Error: Could not load /resources/js/Components/SecondaryButton.vue (imported by resources/js/Pages/Profile/Partials/DeleteUserForm.vue): ENOENT: no such file or directory, open '/resources/js/Components/SecondaryButton.vue'
```

Pārlūkā tas izskatās apmēram šādi:
![image](https://github.com/another-pavels/GroupB-Recepies/assets/6784580/37cf1aef-e5ce-4e3d-bcc3-689a6746bec9)

**Comment by another-pavels** [comment]
Pirms `npm install` Jānodzēš Profile folderi iekš resources/js/Pages
